### ISSUE TITLE
[suggestion] Add option to turn off token animations when teleporting.

### ISSUE THREAD

**Issue by aprusik** [grandseiken/foundryvtt-multilevel-tokens#1]
When you have multiple floors on the same map and they aren't right next to each other it can be annoying to wait for the tokens to move slowly across the map to the right location, so it would be great if it happened instantly.

It looks like you can do it with the _noAnimate Token flag.

I tried doing it myself, but I haven't really done anything with the Foundry API before and I couldn't figure it out, but I might take another stab at it later if you don't decide to do it yourself.

**Comment by grandseiken** [comment]
Sounds good, I'll do it when I have some time

**Comment by grandseiken** [comment]
Should be working in 0.3.0
