### ISSUE TITLE
[question] Will this be functional for v9 stable release on Monday?

### ISSUE THREAD

**Issue by germandrewboat** [grandseiken/foundryvtt-multilevel-tokens#110]
Hope all is well, just checking on v9 compatibility. Thanks!

**Comment by MagicOriole** [comment]
Seems to pop some "Canvas drawing failed for the token layer" errors

**Comment by Merudo** [comment]
The teleports don't work on V9 for me.

**Comment by SeanStoves** [comment]
Teleports appear to work fine on-map,  However, when you go to a difference scene it errors out.

**Comment by grandseiken** [comment]
AFAIK all features now work fine on V9 with the new 1.5.3 release - please file a new issue if you still have problems.
