### ISSUE TITLE
Token cloning broken in Foundry V9

### ISSUE THREAD

**Issue by MorganVergara** [grandseiken/foundryvtt-multilevel-tokens#111]
Token cloning has an issue with Foundry V9. If you have a token in the source area, and the token is invisible, it is visible in the cloned area.  Verified that this is in V9. Still works as intended in V8.6. V9 made major changes to lighting and visibility, so I suspect this is the issue.

**Comment by grandseiken** [comment]
Should be fixed in 1.5.3
