### ISSUE TITLE
The Future of Multilevel Tokens - Communication Is Key

### ISSUE THREAD

**Issue by tjlanza** [grandseiken/foundryvtt-multilevel-tokens#115]
I'm certain there are a large number of Foundry VTT users that have made Multilevel Tokens an important part of their workflow. However, this project has not been updated since June 2021. Foundry VTT v9 began development in August 2021, and reached stable in December 2021. It is now March 2022, and there has been no visible movement on ensuring this module is compliant and compatible with Foundry VTT v9.

I fully understand that this is an unpaid, volunteer project, and there is no expectation that it will be maintained forever. However, if this module is no longer going to be maintained, please provide clear communication of such. Knowledge that no updates are forthcoming will let those of us who rely on it know that we need to switch to alternative solutions.

**Comment by grandseiken** [comment]
Apologies for the delay. I don't intend to leave this unmaintained, just unfortunately my DnD group is on hiatus so I'm not actively using Foundry at moment, and that makes it harder to stay in the loop and find time to devote to this. FWIW the module was more or less functional in version 9 already, with only one or two compatibility issues reported - I have just released an updated version that should fix everything up for V9 compatibility.

**Comment by Fallayn** [comment]
For what its worth, thanks for the update, it is appreciated greatly, as Multilevel Tokens is such a great tool and core part of my (and seemingly many others) Foundry workflow.

Perfectly understandable to slow down if you currently don't neet it - but still, thanks! Even if you decide to drop it, thanks for creating this awesome addition to Foundry.
