### ISSUE TITLE
Updating the Author value on drawings throws errors

### ISSUE THREAD

**Issue by sneat** [grandseiken/foundryvtt-multilevel-tokens#117]
Attached is the error being thrown when MLT tries to update the author value of the drawings on a scene:

![image](https://user-images.githubusercontent.com/293277/159599042-b60520b0-532b-48ac-a2a2-bb8c2a39d6d8.png)

This happens because `d._id` is undefined. It should either be `d.id` or `d.data._id`.

![image](https://user-images.githubusercontent.com/293277/159599162-e5a1a036-965b-4a63-846c-c230a4148a55.png)

Steps to replicate:

1. Create a scene with MLT drawings in it.
2. Export the scene to a module compendium.
3. Create a new world (so that the GM userID changes).
4. Import the scene from the module compendium. When it first loads, it will throw these errors.

**Comment by grandseiken** [comment]
Thanks!
