### ISSUE TITLE
locked x-pos

### ISSUE THREAD

**Issue by Benjaneer** [grandseiken/foundryvtt-multilevel-tokens#119]
I've got a rectangle and in another scene I have the same size rectangle rotated 90 degrees (one players view will be from the side while the other will be from the bottom, and there will be another from the top and left, like they're sitting around a table).  The problem is that the position of the cloned (both are source and destination) rectangle at 90 degrees for some reason is locked at -300, it lets me change the y position but every time I try to change the x-position (even when I just drag it) it jumps back to the left.

**Comment by grandseiken** [comment]
I can rotate and move rectangles just fine, sounds like the problem is coming from somewhere else?
