### ISSUE TITLE
Select or Target the token for Macro use

### ISSUE THREAD

**Issue by brunocalado** [grandseiken/foundryvtt-multilevel-tokens#12]
Hi.

Great work!!!

Is it possible to make the token be selected or targeted so you can apply macros to it?

**Comment by grandseiken** [comment]
Sorry, I'm not sure I follow exactly - which feature are you talking about? Which token? Is this for the new `@macro` regions?

**Comment by brunocalado** [comment]
> Sorry, I'm not sure I follow exactly - which feature are you talking about? Which token? Is this for the new `@macro` regions?

Yes. It's about the new macro feature.

There is some macros the require a selected/targeted  token.

I'll give an example.

There is a macro in tokenmagic that apllies an effect on a selected token.

I want to trigger a macro in the token which entered the macro zone. But, it must be selected/targeted.

**Comment by pints1ze** [comment]
this might be doable with the provided region, scene, token variables...  in your macro you might be able to do:

```
let oldTargets = game.user.targets;
let newTarget = new Set().add(token); // 'token' will be the token that entered the region
game.user.targets = newTarget
```

// DO THE THING

**Comment by grandseiken** [comment]
Yeah, the `token` variable is provided for this purpose.

Auto-selecting the token that entered could be a bit awkward: for one a bit surprising if you're not expecting that behaviour, and secondly, I believe the GM cannot select the token if they're not currently viewing the scene where the `@macro` region triggered, so the macro wouldn't work properly in that case.

I think it'd be worth trying as @pints1ze suggested, though you might need to copy the macro and modify it slightly I think it's a more robust solution.
