### ISSUE TITLE
Multilevel Token Breaks Midi-QoL Roll Automation

### ISSUE THREAD

**Issue by King-Khufu** [grandseiken/foundryvtt-multilevel-tokens#122]
With Multilevel Token active Midi-QoL automation does not work. No roll result is posted to the chat whatsoever. Below is a snapshot of the console when you try to make a roll targeting another actor with MLT activated.

![image](https://user-images.githubusercontent.com/87103761/167986008-860b924a-3d67-4d05-ba93-14fe26a90ab3.png)

Console with MLT deactivated showing a successful role.

![image](https://user-images.githubusercontent.com/87103761/167986419-c5fceefe-19da-4d4a-b6b5-f70eea4d2c1a.png)

I have confirmed via "Find the Culprit" that the issue only happens when MLT is activated.

**Comment by grandseiken** [comment]
I hope this should be fixed by the new option to have cloned tokens share actors in v1.6.0.
