### ISSUE TITLE
Compatibility with Pending v10?

### ISSUE THREAD

**Issue by tjlanza** [grandseiken/foundryvtt-multilevel-tokens#125]
Greetings,

Has any work been undertaken to ensure compatibility with the forthcoming v10 of Foundry?

Thanks!

**Comment by danil0man** [comment]
Please, Can this be updated to version 10? I use it in many of my maps and it would be great if it gets updated to the version 10.

**Comment by grandseiken** [comment]
1.6.0 out with support for version 10 and a couple other little things.
