### ISSUE TITLE
MLT Drawing Configuration tab missing. 

### ISSUE THREAD

**Issue by CatbotTsumi** [grandseiken/foundryvtt-multilevel-tokens#128]
The multilevel token tab menu in the  drawing configuration menu is missing. It's still missing even after disabling every module except MLT.
Foundry version: 9 build 280
system DnD5e 1.6.3

**Comment by grandseiken** [comment]
When v1.6.0 was released, initially it was accidentally not properly marked as incompatible with foundry version 9. This is fixed now but it might have been auto-updated in the meantime. v1.6.0 is only compatible with foundry version 10, you need to downgrade to v1.5.x while you are still on foundry 9.

**Comment by CatbotTsumi** [comment]
Okay downgrading, worked! Seems good. Thank you.
