### ISSUE TITLE
Feature Request: @macro regions being able to use Advanced Macros from The Furnace.

### ISSUE THREAD

**Issue by pints1ze** [grandseiken/foundryvtt-multilevel-tokens#13]
My current use would be to allow having one macro for traps.  having the region @macro:DoTrapAttack 'Traps' 'Pit' would be very cool.

**Comment by grandseiken** [comment]
Something similar was suggested on discord. Unfortunately the Furnace macro extensions work in a way that makes them a bit tricky to reuse. It should be fairly easy to support passing arguments like that anyway, without depending on Furnace, and still have it work in way that's compatible with Furnace macros (though it wouldn't support other advanced macro features like recursive macros without doing something trickier I think)

**Comment by pints1ze** [comment]
That would be awesome! My use case would just need the arguments as you suggest.

**Comment by grandseiken** [comment]
Macro arguments now supported in 1.0.0.
