### ISSUE TITLE
Feature Request: Click to Activate

### ISSUE THREAD

**Issue by TacoSupreme** [grandseiken/foundryvtt-multilevel-tokens#15]
It would be great to get the ability to click to activate a teleport for things like trap doors, ladders, holes or other things where you might not want to just step on to them.

**Comment by grandseiken** [comment]
How do you imagine this working? The players clicking, or the GM clicking? What would they click? Right now since the drawings would usually be hidden there isn't really anything for the players to click on.

**Comment by TacoSupreme** [comment]
I think you would have a hidden drawing at the same location as a map feature that you want clickable.  I guess the players wouldn't have any visual feedback, so that might be an issue.

I did some of this with trigger happy and an invisible token and that works ok, but it is a lot more setup than your mod is and I had some duplicated token problems as well.

**Comment by ryanwalder** [comment]
Along the same lines this would be cool for elevators with a floor selection button (in more modern campaigns).

Something along the lines of:

0. Enter teleport space
0. List of destinations pops up
0. Click destination, teleports token(s) within the space to that destinations

You could potentially then permission the popup list for GMs/Players or possibly even permission per destination so you could create a puzzle where it shows destinations X and Y with a hidden destination Z until the GM unhides it manually or is triggered by something.

Kind of like the hospital in one of the Silent Hill games where the hospital is empty till you explore the first 3 floors then get back in the elevator and the button for floor 4 appears.

**Comment by grandseiken** [comment]
I'm not opposed to doing something like this (definitely sounds useful), the tricky bit is just coming up with the UI part so that it fits with the rest of the module and is as straightforward to use as folks expect :)

@tacosupreme would ryan's suggestion of a dialog box that pops up automatically (presumably with a "teleport" or "don't teleport" option in your case) work for you? Avoiding the extra step of setting up a clickable thing the players can see might make things easier, although automatic popups could get a bit annoying if you don't actually want to teleport, and if there are multiple options to choose from you'd need a way to provide the text to display on those options as well.

A simpler option I've considered is something like just the option to require holding the Alt key (for example) while moving a token into a teleport space to trigger teleports. Not as discoverable as clickable things or dialog boxes, but certainly very simple to set up. Would need a separate system to handle the "choose destination" part though.

**Comment by TacoSupreme** [comment]
I might use the pop up dialog, or may stick with just using trigger happy for clickable things.  I would need to use it a bit and see if the pop up is too annoying for my players.  Trigger Happy is a bit harder to set up and I have had issues with multiple tokens being spawned and other things that I haven't experienced with multilevel tokens.

The way I thought it would work is you have a map feature that you want clickable like a magical portal, or a ladder.  You place a drawing over the feature that you name and hide.  The player clicks on where the drawing is (the same place as the map feature like a ladder) and it then activates the teleport as if they had moved into a region.  Putting them at the matching spot in the destination drawing.

I can see how having everything only trigger on a move into a region would make more sense with how the module works and the pop up dialog idea seems like a good way to implement this and stay within that scope.  I don't know if it would be better or worse than trigger happy with my players until I play it with them.

**Comment by grandseiken** [comment]
> The player clicks on where the drawing is (the same place as the map feature like a ladder) and it then activates the teleport as if they had moved into a region. Putting them at the matching spot in the destination drawing.

So you're imagining that you'd have to move your token into the teleport region first, _before_ clicking on the region? I guess if the teleport spot is obvious enough that could work. If the region is small there could be some confusion about whether the player is just trying to click on their token, or trying to click to activate the region though.

**Comment by grandseiken** [comment]
How about something like this:

* New option for teleport **In** regions: Activate via map note
* Tokens don't teleport automatically when they move into those regions
* When a player clicks a map note inside the region, any token they control in the region gets teleported
* When a GM clicks the map note all tokens in the region get teleported
* Possible extra option: destination select dialog box, only works with map-note-activated teleports

**Comment by grandseiken** [comment]
I have added the option to activate teleports with clickable map notes in v1.3.0. Filed https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/23 to track the separate issue of choosing destinations with a dialog box. Closing this ticket as the original request has been fulfilled as far as I'm aware. Thanks for bearing with me on this one.
