### ISSUE TITLE
[Feature] Work with the Regions Feature

### ISSUE THREAD

**Issue by ChasarooniZ** [grandseiken/foundryvtt-multilevel-tokens#154]
Converting some of the Module's Features to region as so (in my thoughts):
- Cloning
  - Most important unique feature to copy, worth doing it for sure
- Teleport 
  -  Unnecessary to port, already included in core
- Levels
  - Would be a nice holdover until levels becomes core

**Comment by grandseiken** [comment]
You'll probably want to files this here instead now: https://github.com/BeneosBattlemaps/Beneos-Multilevel-Tokens
