### ISSUE TITLE
[SECURITY] Clarify maintainer change in README / on GitHub / on foundryvtt.com

### ISSUE THREAD

**Issue by DrMcCoy** [grandseiken/foundryvtt-multilevel-tokens#155]
You should probably clearly state that [Beneos](https://github.com/BeneosBattlemaps/Beneos-Multilevel-Tokens/) took over development/maintainership of this module, otherwise this might look like a hostile take-over or a security issue.

You might want to state it in the README.md, with a link to the new URL, and additionally maybe set the GitHub repo to archived, and switch off the issue tracker and PRs. You might also say that on the module description on foundryvtt.com, and change the Project URL to the new location as well.

**Comment by grandseiken** [comment]
Done
