### ISSUE TITLE
Feature Request: Scale Token Options in Cloned Regions

### ISSUE THREAD

**Issue by Dumbhuman** [grandseiken/foundryvtt-multilevel-tokens#18]
I love using this to depict tokens on lower levels of maps, but I'd love it even more if I could add some size perspective by making the cloned tokens shown on lower levels actually appear smaller.  Being able to apply a scale multiplier option in addition to the tint option would be fantastic, especially since the logic to make them region-specific already exists.

I can get this effect currently by making my lower level and its corresponding cloned area larger than the top level and its cloned area, but for extreme perspectives such as very high cliffs it means using very large maps for the lower levels which can be a bit unwieldy.

**Comment by grandseiken** [comment]
I hadn't thought of that, it's a cool idea and should be pretty easy to do.

**Comment by grandseiken** [comment]
Added on v1.3.0
