### ISSUE TITLE
Issues with token mold

### ISSUE THREAD

**Issue by Moerill** [grandseiken/foundryvtt-multilevel-tokens#2]
https://github.com/Moerill/token-mold/issues/22

There seems to be an issue where the tokens you create does not have an "actor" as attribute.
For some reason it gets through the check if the token has an actor, but the token seems to lose the actor attribute later on.

The way i notice it only happens when the "shadowed token" gets created.

You got any idea whats happening or if you can solve this on your end?  since on my end there is not much to do besides adding checks on like every line, which shouldn't be needed.

**Comment by grandseiken** [comment]
I'll change the code to set the `actor` attribute on the dummy tokens to an empty string (`""`), which is the same as you get if you set the actor to "None" in the UI, will that resolve the problem?

**Comment by grandseiken** [comment]
Have done that in 0.3.0, closing for now but let me know if there's anything else I can do

**Comment by DarKDinDoN** [comment]
@grandseiken still have these errors with multilevel-tokens enabled:

```javascript
TypeError: Cannot read property 'data' of null
    at o._setCreatureSize (token-mold.js:528)
    at o._setTokenData (token-mold.js:251)
    at token-mold.js:238
    at Function._call (foundry.js:2210)
    at Function.call [as __furnace_original_call] (foundry.js:2195)
    at Function.callOriginalFunction (Patches.js:57)
    at Function.<anonymous> (Debug.js:42)
    at Scene.createEmbeddedEntity (foundry.js:9979)
    at multilevel.js:507
```

**Comment by Moerill** [comment]
cause token mold isn't updated to do its side of the work.
