### ISSUE TITLE
Making Macros work with Player tokens

### ISSUE THREAD

**Issue by Siddasloths** [grandseiken/foundryvtt-multilevel-tokens#22]
It's most certainly an issue on my end but it never hurts to ask.

Id like to make it so when a player token enters a trap area it auto triggers the proper saving throw.
however when I link the standard dex save macro to the triggering area it give me an error 

RefferenceError: actor is not defined

**Comment by grandseiken** [comment]
You could use `token.actor` before, but from v1.3.0 `actor` will work as well for greater compatibility with standard macros.
