### ISSUE TITLE
Foundry 0.7.4 Multilevel toksen duplication with Furnace

### ISSUE THREAD

**Issue by Webwra** [grandseiken/foundryvtt-multilevel-tokens#27]
When I tried to make a macro run with Multilevel tokens in 0.7.4 I realised that there are two of everything related to Multilevel tokens, as you can see from the pictures, and every option (cloning, teleport, triggers, etc.) is on by default.

When I set a macro for example in one of the posssible locations, it overwrites it with the combination of the two locations.
For example I write **Macro1** in the first Macro region and **Macro2** in the second, I update reopen Multilevel tab and both regions are overwritten as **Macro1,Macro2**.

It seems to be caused by The Furnace module, but these two worked together with 0.6.6.
Not sure if it needs to be fixed in your side or Furnaces side, but I will post this to both.

### ![Duplicated option](https://user-images.githubusercontent.com/38015643/96331686-9acd1080-105f-11eb-8e87-2d5b6a7b4cba.JPG)
![Setup 1](https://user-images.githubusercontent.com/38015643/96331687-9b65a700-105f-11eb-9a3c-d3ef125b5959.JPG)
![Setup 2](https://user-images.githubusercontent.com/38015643/96331688-9bfe3d80-105f-11eb-9abe-2136922ad187.JPG)
![Setup 3](https://user-images.githubusercontent.com/38015643/96331689-9bfe3d80-105f-11eb-888d-082753353001.JPG)
### ### ### ### `__`

**Comment by grandseiken** [comment]
See https://github.com/kakaroto/fvtt-module-furnace/issues/62

**Comment by grandseiken** [comment]
Closing as I believe this is now fixed in Furnace 2.3.1
