### ISSUE TITLE
Settings Menu Shows Duplicate Options (Cannot Create Level Based Teleports)

### ISSUE THREAD

**Issue by Tetraplasm** [grandseiken/foundryvtt-multilevel-tokens#31]
Hello,

Upon a fresh install of Multilevel Tokens, when I go to the drawing tools, there are two menus for Multilevel:
![Screen Shot 2020-10-22 at 1 21 04 PM](https://user-images.githubusercontent.com/73313551/96925759-7d39e580-1469-11eb-9858-047dccc7a0ac.png)

Upon selecting one, both are highlighted, and all the menu settings are shown twice.
![Screen Shot 2020-10-22 at 1 22 07 PM](https://user-images.githubusercontent.com/73313551/96925856-a65a7600-1469-11eb-8482-ea419ebc2d11.png)
![Screen Shot 2020-10-22 at 1 22 20 PM](https://user-images.githubusercontent.com/73313551/96925870-aa869380-1469-11eb-9492-cf25b4889a66.png)

When I double click a drawing to add level information and set up functionality, some of the fields are automatically filled in with commas or "undefined."
![Screen Shot 2020-10-22 at 1 23 03 PM](https://user-images.githubusercontent.com/73313551/96925971-d3a72400-1469-11eb-87c6-3285e6270146.png)

I tried disabling everything except for "level" (and making sure to not disable functionality for the region): 
![Screen Shot 2020-10-22 at 1 26 59 PM](https://user-images.githubusercontent.com/73313551/96926372-56c87a00-146a-11eb-944a-1b11cc4ea5e3.png)

Upon setting *both* of the "Level" settings to 1 (there are two because the menu, as mentioned above, duplicates everything) this is what I get:
![Screen Shot 2020-10-22 at 1 27 47 PM](https://user-images.githubusercontent.com/73313551/96926426-647dff80-146a-11eb-8422-35f369d15c55.png)

I'm not sure what I'm doing wrong. But it seems like the duplicate menus are messing things up, and that seems like a bug.

**Comment by grandseiken** [comment]
Hi, this is due to some other module you are using not being properly updated for Foundry 0.7.x yet. Most likely it is the Furnace module, which was fixed recently. If you update the Furnace module it should resolve the problem.
