### ISSUE TITLE
[Feature] Allow to define independent IDs for IN and OUT

### ISSUE THREAD

**Issue by PalaNolho** [grandseiken/foundryvtt-multilevel-tokens#32]
This module works amazingly when the portals are tow ways (A ->B and B->A).
However, when you want to have teleports that are 2 ways but for different targets, it's difficult to do and very cumbersome.

The deprecated Teleporter module had something very nice with regard to this and I think we could use it on this module.

My suggestion would be to continue to define if the region can be used for **In** or Out**OUT** BUT add an ID for in and another one for out.

the IN id should be used on as the out of any teleport that intends to send a token to this region
the OUT id should be used to define to which region this teleport should send the token.

Ultimately we don't even need the flags and something like In ID and out ID would suffice (no ID defined means the region doesn't implement the corresponding functionality (ex: no In ID means that it won't be possible to send tokens to this region)

I think this would make it much more versatile while keeping the same behaviour.

Please consider it.

Many thanks.

**Comment by grandseiken** [comment]
You can achieve the same effect by using multiple overlapping regions, and enable In or Out only on each one, so I don't think this is a high-priority feature to add.
