### ISSUE TITLE
error with token hotbar module

### ISSUE THREAD

**Issue by rinnocenti** [grandseiken/foundryvtt-multilevel-tokens#34]
![image](https://user-images.githubusercontent.com/3178127/97354999-08094e80-1875-11eb-8166-72a60d0b3db0.png)
When creating duplicates of the tokens, the hotbar module tries to find your references and does not, which results in an error.

**Comment by grandseiken** [comment]
I discussed this issue briefly with the author of the token hotbar module on https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/14 and I see you've raised an issue there (https://github.com/janssen-io/foundry-token-hotbar/issues/31) as well.

I will leave this issue open for visibility for now but I don't believe there is anything I can do on the multilevel tokens end here.

**Comment by janssen-io** [comment]
Update from Token Hotbar's side: it's still on my radar, but unfortunately, I haven't had a lot of time to develop the module further lately.
