### ISSUE TITLE
Allow for negative width/height on drawings

### ISSUE THREAD

**Issue by Lazytron** [grandseiken/foundryvtt-multilevel-tokens#37]
Since drawings cannot currently be mirrored x/y without using negative values, currently mirrored zones throw errors complaining about tokens having negative width/height. It would be nice if instead of throwing an error the negative token values were parsed as a mirror X/Y (+/- any necessary offset) to create a mirror realm type of thing.

**Comment by grandseiken** [comment]
Have you tried using the `Mirror horizontally` / `Mirror vertically` settings which are specifically intended for making mirrored clone regions? You shouldn't need to set width/height to negative values.

**Comment by grandseiken** [comment]
I will also just take the absolute width/height when cloning though just to avoid errors
