### ISSUE TITLE
TypeError: Cannot read property 'owner' of undefined

### ISSUE THREAD

**Issue by jacobjorvang** [grandseiken/foundryvtt-multilevel-tokens#38]
I'm getting lots of these errors on startup in my 0.7.5 PF2e 1.10.15 world when Multilevel Tokens is enabled, even when it's the only mod. I don't get the errors in a fresh PF2e world with that module enabled though. Of course I'm actually using the module for teleporting and cloning in my game world as opposed to the fresh world. Another different is my game world was created in 0.6.6 a few months ago. I haven't seen anything really go wrong in the game.

**Comment by jacobjorvang** [comment]
![Uploading Screenshot 2020-11-02 at 21.58.34.png…]()

**Comment by jacobjorvang** [comment]
<img width="552" alt="Screenshot 2020-11-02 at 21 58 34" src="https://user-images.githubusercontent.com/5146879/97959411-9c147200-1daf-11eb-84ff-290bace5f080.png">

**Comment by grandseiken** [comment]
See this section from the README:

> Note that, by necessity, cloned tokens are not associated with any actor, and this can sometimes cause compatibility issues with other macros or modules. Foundry allows a token to have no actor, but, as this is a somewhat unusual case, it's often not accounted for. Most commonly, this can result in the macro or module throwing an error like TypeError: Cannot read property 'data' of null.

The issue is almost certainly due to the PF2e System assuming that a created token must be linked to a real actor via its `actor` field and not checking it for null/undefined.

**Comment by jacobjorvang** [comment]
Thank you for the explanation. I will suggest a fix on the PF2e side.
