### ISSUE TITLE
Feature Request: option to enable/disable storing the latest settings each time

### ISSUE THREAD

**Issue by itamarcu** [grandseiken/foundryvtt-multilevel-tokens#39]
Currently, if you create a drawing with certain teleportation/macro/etc, the next drawing of that shape you create will start with the same settings.  I would like the option to disable this if possible!

**Comment by grandseiken** [comment]
> Currently, if you create a drawing with certain teleportation/macro/etc, the next drawing of that shape you create will start with the same settings. I would like the option to disable this if possible!

This is not an intended feature and doesn't happen for me. I've never seen that happen. Do you have steps to reproduce this issue?

**Comment by itamarcu** [comment]
This is the same behavior that core Foundry has with drawings.  When you edit a drawing, you'll even see a button at the bottom of the popup that says "Reset Defaults" - implying that everything you update in the configuration window is saved as default to be used the next time you create a drawing.

**Comment by grandseiken** [comment]
The "reset defaults" button only appears if you use the "configure default drawing" foundry option, which might lead to the behaviour you described, since that's its purpose. If you just edit a drawing normally (by double-clicking it) the changes you make don't get saved for next time.
