### ISSUE TITLE
Bug: Problems Moving/Deleting Journal Notes on Map

### ISSUE THREAD

**Issue by Dumbhuman** [grandseiken/foundryvtt-multilevel-tokens#45]
When I have the module enabled, I find that I often can't move journal notes or delete them from the map.  If I want either of those functionalities to work consistently, I disable the module and then I'm able to move/delete as normal.

**Comment by 00zim00** [comment]
I also have the same issues. However if you install the "Select tool everywhere" mod you can drag-selection box it then press del to remove it. Not as intuitive but it works.

**Comment by grandseiken** [comment]
Should be resolved with upcoming version.
