### ISSUE TITLE
Offset activation map notes not working in Right or Bottom positions

### ISSUE THREAD

**Issue by GebotheBardbarian** [grandseiken/foundryvtt-multilevel-tokens#49]
When a teleport activation map note is placed on a half-square located on the bottom or right side of the teleport region, teleport activation does not work. However, activation still works if place on the left or top side of the region.

Activation does not work:
![image](https://user-images.githubusercontent.com/74924680/102828255-123d5a00-4399-11eb-9fea-6f0d8ed77917.png)

Activation does work:
![image](https://user-images.githubusercontent.com/74924680/102828353-61838a80-4399-11eb-9603-5ddcea3f4614.png)

**Comment by grandseiken** [comment]
There should already be a margin for error for placement of the note, and the case you described works for me, but I have increased the margin slightly in the next version anyway in case. Please reopen if it still doesn't work for you
