### ISSUE TITLE
support/documentation - how to manage multi-level stairs

### ISSUE THREAD

**Issue by scooper4711** [grandseiken/foundryvtt-multilevel-tokens#51]
Suppose I have mutlilevel stairs, i.e. a round stairwell that spans multiple floors.
How can I control that I want to go from floor 1 to 2, then 2 to 3 then 3 to 4, or suppose I'm on 2 and want to go down?
The issue being that the @stair actor is in the same relative location from floor to floor, so the current implementation seems to pick nearly at random.
You don't have to change anything, just document how I can make it so that players can select which direction they want to go. Note that the stairwell is exactly one square wide and high.

**Comment by grandseiken** [comment]
Are you saying that you have a set of stairs on a single grid square that goes _both_ up and down?

If so, there isn't any good way to allow choosing at the moment. https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/23 would make it possible to choose a destination, but for now the typical solution would to be to have the "up" and "down" staircases on different grid squares.

**Comment by scooper4711** [comment]
Yes. You can close this one as a dupe of the other.
