### ISSUE TITLE
Can't interact with the settings

### ISSUE THREAD

**Issue by Dracodis** [grandseiken/foundryvtt-multilevel-tokens#53]
Hello there! I'm having trouble with the multillevel tokens module. Even though the module is shown as active and the tab appears in the "Drawing Configuration" window, I am unable to actually do anything.  The same goes for the "Textures" tab (though I don't really care about that right now); I can only interact with the "Settings" tab. I've tried refreshing and logging in and out, as has the primary GM for this game (for whom it works), but even though I'm listed as a GM with all the same permissions and am the only one logged in at the time, I can't do anything with it for some reason.

**Comment by grandseiken** [comment]
You likely need to disable the foundry "advanced drawing tools" which conflict with this module.
