### ISSUE TITLE
Feature Request: Unique Drawing Tools

### ISSUE THREAD

**Issue by Greysion** [grandseiken/foundryvtt-multilevel-tokens#63]
Hi,

Thank you for this incredible mod. All of your modifications make Foundry feel like the best possible version of itself.

I wanted to ask, however, and I understand that you will likely turn this down for the obvious reasons;

Currently, you're using the Drawing Tool to implement these features. What are the chances of creating unique tools to accomplish this, to give us a little more fine control over the regions?

Such as;
- No longer requiring journal notes, instead of being inbuilt.
- Being able to toggle the visibility of 'drawings,' like other Foundry elements.
- No overlapping features, so the distinguishment between purposes is clearer.

I believe you are working within quite restrictive boundaries, although I may indeed be stating what is probably obvious to you here. Your mod is incredible, and you should be proud—I certainly can only be thankful.

**Comment by grandseiken** [comment]
Unless something new has happened I'm not aware of, I don't think there is a way to basically create entirely new scene element types within a foundry module. Modules are client-side only, and you can't change the server side (so it wouldn't be able to store them?).

Even if it were possible, I feel that the drawing tools are a pretty good fit and reusing them vastly reduces the amount of code & maintenance burden. Having a better solution for Journal notes might be good though.

You can already toggle the visibility of drawings, though?

So, yeah, unlikely to happen.
