### ISSUE TITLE
[Feature Request/Bug] Drawing new shapes shouldn't retain last multi-level setting

### ISSUE THREAD

**Issue by ElvenChaos** [grandseiken/foundryvtt-multilevel-tokens#64]
Currently, whether intentional or not, drawing new shapes remembers the previous multi-level settings. This can cause the creation of accidental teleports when the shape was meant for something else (such as a label).

If this isn't a bug, then a setting to toggle the functionality off would be wonderful.

Thank you!

**Comment by grandseiken** [comment]
I cannot reproduce this issue. I suspect you accidentally configured the "Default drawing" (the cog option in the drawing menu) which allows you to set default values for new drawings? Please reopen if you are still having this issue
