### ISSUE TITLE
Critical Use Bug: Token Vision not working

### ISSUE THREAD

**Issue by TheBalzan** [grandseiken/foundryvtt-multilevel-tokens#67]
While this mod is active token vision does not work as expected. Vision does not update as token moves. Players have to deselect their tokens and reselect them to see what they should see.
This makes the AWESOME features of this mod unusable.

**Comment by grandseiken** [comment]
Are you sure? I cannot reproduce, vision works fine as normal for me.

**Comment by TheBalzan** [comment]
Yes. As soon as a token moves the tokens image stays where the token was a
moment ago. This may be exacerbated by having multiple levels on a map or
even after a token travels levels.
This issue was affecting my players until I disabled the mod.

**Comment by grandseiken** [comment]
As I said, vision works properly for me, and MLT does not add change anything that would interfere with token vision. Can you try with no modules enabled other than multilevel tokens?
