### ISSUE TITLE
Rapid token movement via keyboard scrambles teleportation position

### ISSUE THREAD

**Issue by Varriount** [grandseiken/foundryvtt-multilevel-tokens#68]
As the title says - when moving a token through a teleportation point via arrow keys, "rapid" movement (repeatedly tapping the arrow key) appears to cause strange errors in token positioning.
Some behavior I've seen:
  - A token teleports ok, but after moving to some arbitrary point on the map, gets teleported back to a point near the original "teleport in" spot.
  - A token teleports, and is moved several (10 or more) squares up/down/left/right of the teleport destination, ignoring walls.

**Comment by grandseiken** [comment]
This can definitely be an issue, and I will try to look into seeing if there's anything that can be done, but it might be difficult to do anything about due to the way foundry handles user input / token movement.
