### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BoTKaPyC** [grandseiken/foundryvtt-multilevel-tokens#70]
When the player's token is on the map where I am, everything is fine. As soon as I or the player himself clicks on the transition to another map, I get two errors. all in the screenshots. I use the PF 2e system. When they go to the map where I am, there are no errors in the console. This happens with any scene where the actors move with this mod. As soon as they teleport, I get this error in the console. But if he returns to the stage where I am, there will be no mistake.
![unknown (1)](https://user-images.githubusercontent.com/80960291/112128032-d5773e00-8be7-11eb-9424-47c387367497.png)
![unknown](https://user-images.githubusercontent.com/80960291/112128040-d8722e80-8be7-11eb-9b10-f7acbad69e93.png)

**Comment by grandseiken** [comment]
Most likely, PF2e does not take into account that tokens can be created on a scene that you are not looking at. This is a PF2e issue, you should report it to them.
