### ISSUE TITLE
Token Visibility Toggle During Teleport

### ISSUE THREAD

**Issue by SmokeRaven667** [grandseiken/foundryvtt-multilevel-tokens#72]
I noticed when token teleports on same scene, it is essentially an automated token move which is cool, but without the token visibility toggled, the player will see stuff as token whisks to new location that they should not (since token moves thru walls designated for different levels of map within same scene).

Is this an easy update?

**Comment by grandseiken** [comment]
If you uncheck the `Animate movement` box on both the in and out region, the token will teleport instantly without animating.
