### ISSUE TITLE
Macro Feature Triggers Erroneously on Token Update When Set to Enter and Leave

### ISSUE THREAD

**Issue by Tarbarian** [grandseiken/foundryvtt-multilevel-tokens#73]
As the title says, if you have a trigger set to activate on entrance and leaving and have both functions of the macro update the token in some way (like setting a flag), the action for both entering and leaving will trigger at the same time due to (as far as I can tell) the token updating. As this is difficult to describe, here is the very simple macro that can reproduce the bug.
```
if (event === "enter") {
    console.log(event)
    token.setFlag('pf1','disableLowLight',false)
} else if (event === "leave") {
    console.log(event)
    token.setFlag('pf1','disableLowLight',true)
}
```
It's for PF1e as that is the system I play, but it should be easy to change and have reproduce the issue if you change the flags to something relevant to the system used for testing.

**Comment by grandseiken** [comment]
Thanks for the report, fixed for upcoming version
