### ISSUE TITLE
_getSceneScaleFactor returns wrong value for non hex grids

### ISSUE THREAD

**Issue by nloew** [grandseiken/foundryvtt-multilevel-tokens#74]
https://github.com/grandseiken/foundryvtt-multilevel-tokens/blob/761d643125197871065e21d09b38cdc0fffa3b5f/multilevel.js#L294-L295

IF clause is the wrong way around, should set 1 if false, not hexScale

FIX:
x: scene.data.gridType === GRID_TYPES.HEXODDR || scene.data.gridType === GRID_TYPES.HEXEVENR ? hexScale : 1,
y: scene.data.gridType === GRID_TYPES.HEXODDQ || scene.data.gridType === GRID_TYPES.HEXEVENQ ? hexScale : 1,

Comment:
This is one factor leading to wrong alignment of actors in https://github.com/grandseiken/foundryvtt-vehicles-and-mechanisms when rotating vehicles

see also https://github.com/grandseiken/foundryvtt-vehicles-and-mechanisms/issues/9

**Comment by grandseiken** [comment]
thank you, will fix!
