### ISSUE TITLE
V1.4.0 does not allow map notes to be moved after dropping

### ISSUE THREAD

**Issue by foxreinhold** [grandseiken/foundryvtt-multilevel-tokens#78]
For V 1.4.0 on Foundry 0.7.9 using latest Chrome version - After dropping a map note in a box to be used as an activation switch, you cannot move it anywhere else via subsequent drag and drops.  Downgrading to V 1.3.4 alleviates this issue entirely.

**Comment by grandseiken** [comment]
Thanks for pointing that out, fixed in 1.4.1
