### ISSUE TITLE
wfrp4e & Multilevel Tokens

### ISSUE THREAD

**Issue by StevenEvans1966** [grandseiken/foundryvtt-multilevel-tokens#82]
I am seeing several exceptions (see attached log) relating to missing data on the cloned tokens produced by Multilevel Tokens (v1.4.1)
From: stevenevans1966
wfrp4e: 3.5.1
wfrp4e-core: 1.3.3
wfrp4e-dotr: 1.0.0
wfrp4e-eis: 1.2.2
wfrp4e-rnhd: 1.4.1
wfrp4e-starter-set: 1.4.3
wfrp4e-ua1: 1.0.2

[vtt_log-1620211108862.log](https://github.com/grandseiken/foundryvtt-multilevel-tokens/files/6426563/vtt_log-1620211108862.log)

**Comment by grandseiken** [comment]
Likely fixed by actor linking setting in 1.6.0
