### ISSUE TITLE
Settings not saving for drawings

### ISSUE THREAD

**Issue by Arschev** [grandseiken/foundryvtt-multilevel-tokens#86]
Anytime i edit any of the MLT settings in a drawing and save, its gone the next time i open it
All other modules are disabled as well
![MLToken](https://user-images.githubusercontent.com/79369541/119856826-05d9a200-bee1-11eb-8c63-47adad4a781e.gif)

**Comment by grandseiken** [comment]
Are you on foundry 0.8.x? The module hasn't been updated for that version yet, but should be very soon.

**Comment by Bashadash** [comment]
Hi @grandseiken, do you have an update or an eta when this will be updated?

**Comment by grandseiken** [comment]
See
