### ISSUE TITLE
MLT options not showing in token dialog box

### ISSUE THREAD

**Issue by Morningate** [grandseiken/foundryvtt-multilevel-tokens#88]
I am using Multilevel Tokens v1.4.2 with Foundry v0.7.10, hosted on The Forge. However, with the mod enabled, I do not see the MLT tab in the token dialog box. This happens even when MLT is the only mod enabled in my game. I believe this started after I updated Foundry to 0.7.10.

**Comment by grandseiken** [comment]
Afraid I can't reproduce this issue - shows up fine for me with foundry 0.7.10 on the forge.

> token dialog box

MLT is configured in the settings for _drawings_, not tokens, though, are you looking in the right place?

**Comment by Morningate** [comment]
Oh my gosh. I'm so stupid. I completely forgot where to look.

The tab for MLT is right there on the drawing dialog box.

Thank you for pointing that out. I'm sorry to have wasted your time.
