### ISSUE TITLE
MLT Issues with waypoints

### ISSUE THREAD

**Issue by Squishiest-Grape** [grandseiken/foundryvtt-multilevel-tokens#91]
When moving with the measurement/waypoints tool via [ctrl+drag+space], the last animation occurs after the teleport.  Not only that, but it also breaks teleportation occasionally (Other modules, ie: drag ruler, can make this occur more regularly).  Broken teleports are resolved upon re-load. I've included a video running MLT v1.5.0 (and no other modules) and Foundry v0.8.6

Edit: The video is buggy, I will be posting the correct one on the foundry discord channel.

**Comment by grandseiken** [comment]
This was caused by an issue on foundry's end, I have filed https://gitlab.com/foundrynet/foundryvtt/-/issues/5335 and added an ugly workaround to the module in v1.5.1 for now that should clear things up.

**Comment by Squishiest-Grape** [comment]
I believe this issue was resolved a while ago.  While I have not checked, so much has changes since then with foundry and both modules that I feel the issue as it is documented here is no longer applicable.
