### ISSUE TITLE
Tokens getting deleted after teleporting more than twice.

### ISSUE THREAD

**Issue by Crokos1** [grandseiken/foundryvtt-multilevel-tokens#93]
Made a boat map with different entrances to get to the two top areas and after they go up, then down, then up again they get deleted.

**Comment by grandseiken** [comment]
I haven't seen anything like this, can you provide more details? Are you sure you didn't have another teleport exit with the same identifier on another scene somewhere and they ended up there?

**Comment by Crokos1** [comment]
Yup this was it just checked and there happened to be a teleporter with the
same name in another old scene. Thank you for the help this fixed
everything!

**Comment by grandseiken** [comment]
no problem!
