### ISSUE TITLE
Incompatibility with Drag Ruler on 0.8.6

### ISSUE THREAD

**Issue by vanderleitelesjr** [grandseiken/foundryvtt-multilevel-tokens#95]
If the module Drag Ruler is enabled, there is a visual glitch whenever the token lands on a drawing set to run a macro. For example, I usually use Multilevel Tokens to set up elevation drawings across my maps, to automatically update a token's elevation whenever they move into specific areas, if Drag Ruler is enabled the tokens are sent flying past their intended destination whenever they are dragged into a drawing with the macro that changes their elevation:

![Glitch](https://user-images.githubusercontent.com/40318093/120942655-c7be5880-c700-11eb-9869-1c8da408aa62.gif)

**Comment by vanderleitelesjr** [comment]
The issue is not exactly related to Drag Ruler, as it does happen as well when simply using the Ctrl+Drag native functionality.

**Comment by grandseiken** [comment]
Is this fixed by updating to 1.5.1? (I fixed something very similar with Ctrl+Dragging into teleports)

**Comment by vanderleitelesjr** [comment]
I am using 1.5.1

**Comment by grandseiken** [comment]
I have reproduced the issue, but AFAIK the module isn't really doing anything wrong here. In your macro code, you're running (I guess) `token.update()` to set elevation, and it happens that updating a token while it's animating a ctrl+drag-move already just seems to cause visual glitches with foundry's animation code right now. Not sure if I can work around this.
